services:
  estop:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RCUTILS_COLORIZED_OUTPUT=1
      - ROS_DOMAIN_ID=1
    network_mode: host
    command: ros2 run estop estop_server
    container_name: estop
  keep-alive-estop-talker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RCUTILS_COLORIZED_OUTPUT=1
      - ROS_DOMAIN_ID=1
    network_mode: host
    command: ros2 run keep_alive_estop keep_alive_estop_talker_node
    container_name: keep-alive-estop-talker
  keep-alive-estop-listener:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RCUTILS_COLORIZED_OUTPUT=1
      - ROS_DOMAIN_ID=1
    network_mode: host
    command: ros2 run keep_alive_estop keep_alive_estop_listener_node
    container_name: keep-alive-estop-listener